# Generated by Django 3.1.8 on 2021-04-10 20:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1000, verbose_name='Log')),
                ('content', django_cryptography.fields.encrypt(models.TextField())),
                ('date', models.DateField(max_length=1000, verbose_name='Date')),
            ],
        ),
    ]
