# Generated by Django 3.1.8 on 2021-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20210410_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='user_from',
            field=models.CharField(default='root', max_length=1000, verbose_name='From user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.CharField(default='root', max_length=1000, verbose_name='To user'),
            preserve_default=False,
        ),
    ]
