# Generated by Django 3.1.8 on 2021-04-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20210411_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(max_length=1000, verbose_name='Date'),
        ),
    ]
